stages:
  - publish

publish_package_registry:
  stage: publish
  image: python:3.12.7
  before_script:
    - pip install poetry==1.8.5
    - poetry self add "poetry-dynamic-versioning[plugin]"
  script:
    - poetry config repositories.gitlab https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry config http-basic.gitlab gitlab-ci-token ${CI_JOB_TOKEN}
    - poetry build
    - poetry publish --repository gitlab
  rules:
    - if: '$CI_COMMIT_TAG'
      when: always
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: always
    - when: never
  environment:
    name: package_registry
    url: https://gitlab.com/${CI_PROJECT_PATH}/-/packages