name: Publish Python 🐍 distributions 📦 to PyPI

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

  pull_request:
    branches:
      - main

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cashcow-core
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install poetry==1.8.5
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Build package distributions
        run: |
          poetry build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
            packages-dir: dist/
